// GENERATED by tools/voice/build_voice.py from tools/voice/lexicon.json - do not edit by hand.
// 눈꽃말 (the village language): word id -> hangul spelling, romanisation, meaning, category and the
// Korean stems (kw; '^' = only at the start of a word) that make VillageVoice say this word when a bubble
// contains them, and longer words that contain a stem but mean something else (kwNot: 선물 is not 물).
export const LANGUAGE = { name: '눈꽃말', roman: 'Nunkkot-mal' };
export const WORDS = {
 "hello": {
  "hangul": "뽀얄",
  "roman": "po.yal",
  "ko": "안녕 (만났을 때)",
  "en": "hello",
  "cat": "greet",
  "kw": [
   "안녕",
   "반가",
   "하이",
   "좋은 아침"
  ]
 },
 "bye": {
  "hangul": "뿔룽뿔룽",
  "roman": "pul.lung.pul.lung",
  "ko": "잘 가 / 안녕 (헤어질 때)",
  "en": "bye-bye",
  "cat": "greet",
  "kw": [
   "잘 가",
   "잘가",
   "안녕히",
   "또 봐",
   "또봐",
   "다음에",
   "내일 봐"
  ]
 },
 "thanks": {
  "hangul": "꼬맙뿌",
  "roman": "ko.map.pu",
  "ko": "고마워",
  "en": "thank you",
  "cat": "social",
  "kw": [
   "고마",
   "고맙",
   "감사",
   "땡큐"
  ]
 },
 "welcome": {
  "hangul": "왈랑",
  "roman": "wal.lang",
  "ko": "어서 와",
  "en": "welcome",
  "cat": "social",
  "kw": [
   "어서 와",
   "어서와",
   "어서 오",
   "환영",
   "오셨"
  ]
 },
 "please": {
  "hangul": "뿌띨",
  "roman": "pu.til",
  "ko": "부탁해",
  "en": "please",
  "cat": "social",
  "kw": [
   "부탁",
   "제발",
   "주세요",
   "줄래",
   "해줘",
   "해 줘"
  ]
 },
 "sorry": {
  "hangul": "뮈앙",
  "roman": "mü.ang",
  "ko": "미안해",
  "en": "sorry",
  "cat": "social",
  "kw": [
   "미안",
   "죄송",
   "잘못했"
  ]
 },
 "yes": {
  "hangul": "뉨",
  "roman": "nüm",
  "ko": "응 / 네",
  "en": "yes",
  "cat": "answer",
  "kw": [
   "^응",
   "^네,",
   "^네!",
   "^네~",
   "그래",
   "맞아",
   "알겠",
   "오케이",
   "좋지"
  ],
  "kwNot": [
   "그래도",
   "그래서",
   "그래픽",
   "응원"
  ]
 },
 "no": {
  "hangul": "노뱅",
  "roman": "no.baeng",
  "ko": "아니 / 안 돼",
  "en": "no",
  "cat": "answer",
  "kw": [
   "아니",
   "안 돼",
   "안돼",
   "싫어",
   "몰라"
  ]
 },
 "good": {
  "hangul": "블룸",
  "roman": "blum",
  "ko": "좋아 / 최고",
  "en": "good, great",
  "cat": "feeling",
  "kw": [
   "좋아",
   "좋다",
   "좋은",
   "최고",
   "멋져",
   "멋지",
   "잘했",
   "훌륭",
   "굿"
  ]
 },
 "wow": {
  "hangul": "우와뿅",
  "roman": "u.wa.pyong",
  "ko": "우와!",
  "en": "wow",
  "cat": "feeling",
  "kw": [
   "우와",
   "와!",
   "와~",
   "대박",
   "세상에",
   "굉장"
  ]
 },
 "yummy": {
  "hangul": "냠냠뇹",
  "roman": "nyam.nyam.nyop",
  "ko": "맛있다",
  "en": "yummy",
  "cat": "food",
  "kw": [
   "맛있",
   "맛나",
   "냠",
   "꿀맛",
   "배불",
   "먹고 싶"
  ]
 },
 "oops": {
  "hangul": "엡뿔",
  "roman": "ep.pul",
  "ko": "앗, 이런",
  "en": "oops",
  "cat": "feeling",
  "kw": [
   "이런",
   "어머",
   "아이고",
   "어이쿠",
   "앗",
   "실수",
   "깜빡"
  ]
 },
 "love": {
  "hangul": "뵐랑",
  "roman": "böl.lang",
  "ko": "사랑해 / 아주 좋아해",
  "en": "love",
  "cat": "feeling",
  "kw": [
   "사랑",
   "좋아해",
   "좋아하",
   "하트",
   "보고 싶",
   "보고싶"
  ]
 },
 "happy": {
  "hangul": "랄랄",
  "roman": "lal.lal",
  "ko": "신나 / 기뻐",
  "en": "happy",
  "cat": "feeling",
  "kw": [
   "신나",
   "기뻐",
   "기쁘",
   "행복",
   "즐거",
   "재밌",
   "재미있"
  ]
 },
 "sad": {
  "hangul": "뮝뮝",
  "roman": "müng.müng",
  "ko": "슬퍼",
  "en": "sad",
  "cat": "feeling",
  "kw": [
   "슬퍼",
   "슬프",
   "속상",
   "울고",
   "눈물",
   "외로"
  ]
 },
 "angry": {
  "hangul": "그롱",
  "roman": "grong",
  "ko": "화나 / 투덜",
  "en": "grumpy",
  "cat": "feeling",
  "kw": [
   "화나",
   "화가 나",
   "화가 났",
   "짜증",
   "흥",
   "투덜",
   "시끄러"
  ],
  "kwNot": [
   "흥정",
   "흥미",
   "흥겨",
   "부흥"
  ]
 },
 "scared": {
  "hangul": "브릅",
  "roman": "brüp",
  "ko": "무서워",
  "en": "scared",
  "cat": "feeling",
  "kw": [
   "무서",
   "깜짝",
   "놀랐",
   "떨려"
  ]
 },
 "tired": {
  "hangul": "뉠롱",
  "roman": "nül.long",
  "ko": "피곤해",
  "en": "tired",
  "cat": "feeling",
  "kw": [
   "피곤",
   "힘들",
   "지쳐",
   "지친",
   "졸려",
   "하품"
  ]
 },
 "funny": {
  "hangul": "킥뽈",
  "roman": "kik.pol",
  "ko": "웃겨",
  "en": "funny",
  "cat": "feeling",
  "kw": [
   "웃겨",
   "웃기",
   "하하",
   "ㅋㅋ",
   "킥킥",
   "농담"
  ]
 },
 "cute": {
  "hangul": "뾰롤",
  "roman": "pyo.rol",
  "ko": "귀여워 / 예뻐",
  "en": "cute, pretty",
  "cat": "feeling",
  "kw": [
   "귀여",
   "귀엽",
   "예뻐",
   "예쁘",
   "이쁘",
   "깜찍"
  ]
 },
 "cold": {
  "hangul": "브르르",
  "roman": "breu.reu.reu",
  "ko": "추워",
  "en": "cold",
  "cat": "nature",
  "kw": [
   "추워",
   "춥",
   "추운",
   "얼어",
   "꽁꽁",
   "시려"
  ]
 },
 "warm": {
  "hangul": "뫼옹",
  "roman": "mö.ong",
  "ko": "따뜻해",
  "en": "warm",
  "cat": "nature",
  "kw": [
   "따뜻",
   "따듯",
   "포근",
   "따끈",
   "뜨끈",
   "난로"
  ]
 },
 "snow": {
  "hangul": "뉘뉘",
  "roman": "nü.nü",
  "ko": "눈 (하늘에서 오는)",
  "en": "snow",
  "cat": "nature",
  "kw": [
   "눈이",
   "눈사람",
   "눈싸움",
   "눈 와",
   "눈와",
   "함박눈",
   "눈밭",
   "눈길"
  ]
 },
 "flake": {
  "hangul": "뉘블룸",
  "roman": "nü.blum",
  "ko": "눈꽃 / 꽃",
  "en": "snowflake, flower",
  "cat": "nature",
  "kw": [
   "눈꽃",
   "꽃"
  ]
 },
 "ice": {
  "hangul": "끼릴",
  "roman": "ki.ril",
  "ko": "얼음",
  "en": "ice",
  "cat": "nature",
  "kw": [
   "얼음",
   "빙판",
   "미끄러"
  ]
 },
 "sun": {
  "hangul": "랭",
  "roman": "raeng",
  "ko": "해 / 햇볕",
  "en": "sun",
  "cat": "nature",
  "kw": [
   "햇빛",
   "햇볕",
   "해가",
   "맑",
   "날씨"
  ]
 },
 "star": {
  "hangul": "쁘릴",
  "roman": "pril",
  "ko": "별",
  "en": "star",
  "cat": "nature",
  "kw": [
   "별",
   "반짝"
  ],
  "kwNot": [
   "특별",
   "별로",
   "별거",
   "이별",
   "별일"
  ]
 },
 "moon": {
  "hangul": "뮌",
  "roman": "mün",
  "ko": "달 / 밤",
  "en": "moon, night",
  "cat": "nature",
  "kw": [
   "달이",
   "밤",
   "저녁"
  ],
  "kwNot": [
   "밤톨",
   "군밤",
   "알밤"
  ]
 },
 "water": {
  "hangul": "올롱",
  "roman": "ol.long",
  "ko": "물 / 바다",
  "en": "water, sea",
  "cat": "nature",
  "kw": [
   "물",
   "바다",
   "파도",
   "강물",
   "강가",
   "호수",
   "찻물"
  ],
  "kwNot": [
   "물감",
   "물건",
   "선물",
   "물어",
   "물으",
   "동물",
   "보물",
   "인물",
   "건물",
   "스물",
   "물개",
   "그물",
   "물고 ",
   "물러",
   "물론",
   "식물"
  ]
 },
 "fire": {
  "hangul": "폭폴",
  "roman": "pok.pol",
  "ko": "불",
  "en": "fire",
  "cat": "nature",
  "kw": [
   "불",
   "모닥",
   "난로"
  ],
  "kwNot": [
   "불러",
   "불어",
   "배불",
   "불림",
   "불편",
   "불안",
   "불쌍",
   "불고기"
  ]
 },
 "wood": {
  "hangul": "똘롬",
  "roman": "tol.lom",
  "ko": "나무 / 장작",
  "en": "tree, wood",
  "cat": "thing",
  "kw": [
   "나무",
   "장작",
   "목재",
   "숲"
  ]
 },
 "home": {
  "hangul": "옴뽁",
  "roman": "om.pok",
  "ko": "집",
  "en": "home",
  "cat": "thing",
  "kw": [
   "집",
   "우리집",
   "방에",
   "방이",
   "내 방",
   "다락방"
  ],
  "kwNot": [
   "뒤집"
  ]
 },
 "village": {
  "hangul": "마울",
  "roman": "ma.ul",
  "ko": "마을",
  "en": "village",
  "cat": "thing",
  "kw": [
   "마을",
   "동네"
  ]
 },
 "fish": {
  "hangul": "퓌뽈",
  "roman": "fü.pol",
  "ko": "생선 / 물고기",
  "en": "fish",
  "cat": "food",
  "kw": [
   "생선",
   "물고기",
   "낚시",
   "연어",
   "참치"
  ]
 },
 "bread": {
  "hangul": "브랑",
  "roman": "brang",
  "ko": "빵",
  "en": "bread",
  "cat": "food",
  "kw": [
   "빵",
   "케이크",
   "쿠키"
  ]
 },
 "eat": {
  "hangul": "묌",
  "roman": "möm",
  "ko": "먹다 / 밥",
  "en": "eat, meal",
  "cat": "food",
  "kw": [
   "먹",
   "밥",
   "식사",
   "점심",
   "간식"
  ],
  "kwNot": [
   "서먹"
  ]
 },
 "hungry": {
  "hangul": "구룩",
  "roman": "gu.ruk",
  "ko": "배고파",
  "en": "hungry",
  "cat": "food",
  "kw": [
   "배고",
   "배가 고",
   "출출",
   "꼬르륵"
  ]
 },
 "money": {
  "hangul": "링들",
  "roman": "ling.dül",
  "ko": "돈",
  "en": "money, coins",
  "cat": "thing",
  "kw": [
   "돈",
   "코인",
   "골드",
   "가격",
   "얼마",
   "비싸",
   "싸다",
   "팔아",
   "사요",
   "살래"
  ],
  "kwNot": [
   "정돈"
  ]
 },
 "boat": {
  "hangul": "블롭",
  "roman": "blop",
  "ko": "배 (타는)",
  "en": "boat",
  "cat": "thing",
  "kw": [
   "배를",
   "배가",
   "보트",
   "항구",
   "선장"
  ],
  "kwNot": [
   "배가 고",
   "배가 아",
   "배가 불"
  ]
 },
 "train": {
  "hangul": "칙폭",
  "roman": "chik.pok",
  "ko": "기차",
  "en": "train",
  "cat": "thing",
  "kw": [
   "기차",
   "열차",
   "역에",
   "역 "
  ],
  "kwNot": [
   "구역",
   "지역"
  ]
 },
 "music": {
  "hangul": "띨롱",
  "roman": "til.long",
  "ko": "노래 / 음악",
  "en": "song, music",
  "cat": "thing",
  "kw": [
   "노래",
   "음악",
   "연주",
   "류트"
  ]
 },
 "work": {
  "hangul": "똑땁",
  "roman": "tok.tap",
  "ko": "일 / 일하다",
  "en": "work",
  "cat": "action",
  "kw": [
   "일해",
   "일하",
   "일이 재밌",
   "작업",
   "만들",
   "짓",
   "공사",
   "열심히",
   "출근"
  ],
  "kwNot": [
   "거짓"
  ]
 },
 "sleep": {
  "hangul": "쿨롬",
  "roman": "kul.lom",
  "ko": "자다 / 잠",
  "en": "sleep",
  "cat": "action",
  "kw": [
   "잠",
   "자자",
   "잘래",
   "자야",
   "쿨쿨",
   "꿈"
  ],
  "kwNot": [
   "잠깐",
   "잠시",
   "잠금"
  ]
 },
 "play": {
  "hangul": "플링",
  "roman": "pling",
  "ko": "놀자",
  "en": "play",
  "cat": "action",
  "kw": [
   "놀자",
   "놀아",
   "놀이",
   "놀러",
   "같이 놀"
  ]
 },
 "go": {
  "hangul": "프룽",
  "roman": "frung",
  "ko": "가자 / 가요",
  "en": "go, let's go",
  "cat": "action",
  "kw": [
   "가자",
   "가요",
   "출발",
   "갈래",
   "가볼",
   "가 볼"
  ]
 },
 "come": {
  "hangul": "욍",
  "roman": "öng",
  "ko": "이리 와",
  "en": "come",
  "cat": "action",
  "kw": [
   "이리 와",
   "이리와",
   "와 봐",
   "와봐",
   "오세요",
   "와요"
  ]
 },
 "help": {
  "hangul": "끌룹",
  "roman": "klup",
  "ko": "도와줘 / 도와줄게",
  "en": "help",
  "cat": "action",
  "kw": [
   "도와",
   "도움",
   "거들"
  ]
 },
 "chief": {
  "hangul": "촌촌님",
  "roman": "chon.chon.nim",
  "ko": "촌장님 (플레이어)",
  "en": "chief (you!)",
  "cat": "person",
  "kw": [
   "촌장"
  ]
 },
 "friend": {
  "hangul": "뮐리",
  "roman": "mül.li",
  "ko": "친구",
  "en": "friend",
  "cat": "person",
  "kw": [
   "친구",
   "이웃"
  ]
 },
 "baby": {
  "hangul": "뽀뉼",
  "roman": "po.nyul",
  "ko": "아기",
  "en": "baby",
  "cat": "person",
  "kw": [
   "아기",
   "^아가"
  ],
  "kwNot": [
   "이야기"
  ]
 },
 "me": {
  "hangul": "뮈",
  "roman": "mü",
  "ko": "나",
  "en": "I, me",
  "cat": "person",
  "kw": [
   "나는",
   "나도",
   "내가",
   "저는",
   "제가"
  ],
  "kwNot": [
   "하나는",
   "혼나는",
   "겁나는",
   "끝나는",
   "신나는",
   "재미나는"
  ]
 },
 "you": {
  "hangul": "냉",
  "roman": "naeng",
  "ko": "너 / 당신",
  "en": "you",
  "cat": "person",
  "kw": [
   "너는",
   "너도",
   "네가",
   "당신"
  ]
 },
 "we": {
  "hangul": "뮈뮈",
  "roman": "mü.mü",
  "ko": "우리",
  "en": "we, us",
  "cat": "person",
  "kw": [
   "우리"
  ]
 },
 "dog": {
  "hangul": "왈뽕",
  "roman": "wal.pong",
  "ko": "강아지",
  "en": "dog",
  "cat": "animal",
  "kw": [
   "강아지",
   "멍멍",
   "콩이",
   "개가",
   "댕댕"
  ],
  "kwNot": [
   "안개가",
   "번개가",
   "베개가",
   "무지개가",
   "콩콩"
  ]
 },
 "cat": {
  "hangul": "미울",
  "roman": "mi.ul",
  "ko": "고양이",
  "en": "cat",
  "cat": "animal",
  "kw": [
   "고양이",
   "야옹",
   "냥이"
  ],
  "kwNot": [
   "사냥"
  ]
 },
 "what": {
  "hangul": "뫼",
  "roman": "mö",
  "ko": "뭐? / 무엇",
  "en": "what?",
  "cat": "question",
  "kw": [
   "뭐",
   "무엇",
   "뭘",
   "무슨"
  ]
 },
 "who": {
  "hangul": "뉩",
  "roman": "nüp",
  "ko": "누구?",
  "en": "who?",
  "cat": "question",
  "kw": [
   "누구",
   "누가"
  ]
 },
 "where": {
  "hangul": "올뮈",
  "roman": "ol.mü",
  "ko": "어디?",
  "en": "where?",
  "cat": "question",
  "kw": [
   "어디"
  ]
 },
 "when": {
  "hangul": "엘뎅",
  "roman": "el.deng",
  "ko": "언제?",
  "en": "when?",
  "cat": "question",
  "kw": [
   "언제",
   "몇 시"
  ]
 },
 "why": {
  "hangul": "퓌웅",
  "roman": "fü.ung",
  "ko": "왜?",
  "en": "why?",
  "cat": "question",
  "kw": [
   "왜"
  ]
 },
 "how": {
  "hangul": "앙뚤",
  "roman": "ang.tul",
  "ko": "어떻게?",
  "en": "how?",
  "cat": "question",
  "kw": [
   "어떻게",
   "어때",
   "어떤"
  ]
 },
 "one": {
  "hangul": "윙",
  "roman": "üng",
  "ko": "하나 (1)",
  "en": "one",
  "cat": "number",
  "kw": [
   "하나",
   "한 개"
  ],
  "kwNot": [
   "하나도"
  ]
 },
 "two": {
  "hangul": "뒬",
  "roman": "dül",
  "ko": "둘 (2)",
  "en": "two",
  "cat": "number",
  "kw": [
   "둘",
   "두 개"
  ],
  "kwNot": [
   "둘게",
   "둘러",
   "둘레"
  ]
 },
 "three": {
  "hangul": "뜨렘",
  "roman": "trem",
  "ko": "셋 (3)",
  "en": "three",
  "cat": "number",
  "kw": [
   "셋",
   "세 개"
  ]
 },
 "four": {
  "hangul": "푀",
  "roman": "fö",
  "ko": "넷 (4)",
  "en": "four",
  "cat": "number",
  "kw": [
   "넷",
   "네 개"
  ],
  "kwNot": [
   "인터넷"
  ]
 },
 "five": {
  "hangul": "뵘뵘",
  "roman": "böm.böm",
  "ko": "다섯 (5)",
  "en": "five",
  "cat": "number",
  "kw": [
   "다섯"
  ]
 },
 "big": {
  "hangul": "볼봄",
  "roman": "bol.bom",
  "ko": "크다 / 많다",
  "en": "big, lots",
  "cat": "size",
  "kw": [
   "큰",
   "커",
   "크다",
   "많",
   "엄청 큰"
  ],
  "kwNot": [
   "커피",
   "커튼"
  ]
 },
 "small": {
  "hangul": "찌밀",
  "roman": "chi.mil",
  "ko": "작다 / 조금",
  "en": "small, a little",
  "cat": "size",
  "kw": [
   "작은",
   "작아",
   "조금",
   "꼬마",
   "조그"
  ]
 },
 "very": {
  "hangul": "뿔",
  "roman": "pul",
  "ko": "정말 / 아주",
  "en": "very, really",
  "cat": "size",
  "kw": [
   "정말",
   "진짜",
   "너무",
   "엄청",
   "완전",
   "아주"
  ],
  "kwNot": [
   "아주머니",
   "아주미"
  ]
 },
 "and": {
  "hangul": "엘",
  "roman": "el",
  "ko": "그리고 / ~랑",
  "en": "and",
  "cat": "filler",
  "kw": []
 },
 "the": {
  "hangul": "델",
  "roman": "del",
  "ko": "그 / 저",
  "en": "the, that",
  "cat": "filler",
  "kw": []
 },
 "youknow": {
  "hangul": "넬",
  "roman": "nel",
  "ko": "있잖아",
  "en": "you know",
  "cat": "filler",
  "kw": []
 },
 "hmm": {
  "hangul": "윔",
  "roman": "üm",
  "ko": "음… (생각 중)",
  "en": "hmm",
  "cat": "filler",
  "kw": []
 },
 "sothen": {
  "hangul": "뚤리",
  "roman": "tul.li",
  "ko": "그래서 / 그러니까",
  "en": "so, then",
  "cat": "filler",
  "kw": []
 },
 "hey": {
  "hangul": "뵬",
  "roman": "byol",
  "ko": "저기 / 이봐",
  "en": "hey, look",
  "cat": "filler",
  "kw": []
 },
 "q": {
  "hangul": "뀰?",
  "roman": "kyul",
  "ko": "~니? (질문 끝말)",
  "en": "question ending",
  "cat": "particle",
  "kw": []
 },
 "excl": {
  "hangul": "얄!",
  "roman": "yal",
  "ko": "~야! (신나는 끝말)",
  "en": "exclamation ending",
  "cat": "particle",
  "kw": []
 },
 "end": {
  "hangul": "뇰",
  "roman": "nyol",
  "ko": "~요 (보통 끝말)",
  "en": "statement ending",
  "cat": "particle",
  "kw": []
 },
 "b01": {
  "hangul": "브뢸까",
  "roman": "bröl.ka",
  "ko": "(뜻 없는 재잘 소리)",
  "en": "(babble)",
  "cat": "babble",
  "kw": []
 },
 "b02": {
  "hangul": "플뤼몹",
  "roman": "flü.mop",
  "ko": "(뜻 없는 재잘 소리)",
  "en": "(babble)",
  "cat": "babble",
  "kw": []
 },
 "b03": {
  "hangul": "가릴롭",
  "roman": "ga.ril.lop",
  "ko": "(뜻 없는 재잘 소리)",
  "en": "(babble)",
  "cat": "babble",
  "kw": []
 },
 "b04": {
  "hangul": "쁠림빽",
  "roman": "plim.paek",
  "ko": "(뜻 없는 재잘 소리)",
  "en": "(babble)",
  "cat": "babble",
  "kw": []
 },
 "b05": {
  "hangul": "뛸락",
  "roman": "tül.lak",
  "ko": "(뜻 없는 재잘 소리)",
  "en": "(babble)",
  "cat": "babble",
  "kw": []
 },
 "b06": {
  "hangul": "발뤼",
  "roman": "bal.lü",
  "ko": "(뜻 없는 재잘 소리)",
  "en": "(babble)",
  "cat": "babble",
  "kw": []
 },
 "b07": {
  "hangul": "끄림봅",
  "roman": "krim.bop",
  "ko": "(뜻 없는 재잘 소리)",
  "en": "(babble)",
  "cat": "babble",
  "kw": []
 },
 "b08": {
  "hangul": "뇔빡",
  "roman": "nöl.pak",
  "ko": "(뜻 없는 재잘 소리)",
  "en": "(babble)",
  "cat": "babble",
  "kw": []
 },
 "b09": {
  "hangul": "뜨뤼빅",
  "roman": "trü.bik",
  "ko": "(뜻 없는 재잘 소리)",
  "en": "(babble)",
  "cat": "babble",
  "kw": []
 },
 "b10": {
  "hangul": "뽈뤽",
  "roman": "pol.lük",
  "ko": "(뜻 없는 재잘 소리)",
  "en": "(babble)",
  "cat": "babble",
  "kw": []
 },
 "b11": {
  "hangul": "빔블로",
  "roman": "bim.blo",
  "ko": "(뜻 없는 재잘 소리)",
  "en": "(babble)",
  "cat": "babble",
  "kw": []
 },
 "b12": {
  "hangul": "프륄랄",
  "roman": "frü.lal",
  "ko": "(뜻 없는 재잘 소리)",
  "en": "(babble)",
  "cat": "babble",
  "kw": []
 },
 "b13": {
  "hangul": "까블림",
  "roman": "ka.blim",
  "ko": "(뜻 없는 재잘 소리)",
  "en": "(babble)",
  "cat": "babble",
  "kw": []
 },
 "b14": {
  "hangul": "댈롭",
  "roman": "dae.lop",
  "ko": "(뜻 없는 재잘 소리)",
  "en": "(babble)",
  "cat": "babble",
  "kw": []
 },
 "b15": {
  "hangul": "롬뷜",
  "roman": "lom.bül",
  "ko": "(뜻 없는 재잘 소리)",
  "en": "(babble)",
  "cat": "babble",
  "kw": []
 },
 "b16": {
  "hangul": "글뢰모",
  "roman": "glö.mo",
  "ko": "(뜻 없는 재잘 소리)",
  "en": "(babble)",
  "cat": "babble",
  "kw": []
 },
 "b17": {
  "hangul": "퀼뽀릭",
  "roman": "kül.po.rik",
  "ko": "(뜻 없는 재잘 소리)",
  "en": "(babble)",
  "cat": "babble",
  "kw": []
 },
 "b18": {
  "hangul": "밸삑",
  "roman": "bael.pik",
  "ko": "(뜻 없는 재잘 소리)",
  "en": "(babble)",
  "cat": "babble",
  "kw": []
 },
 "b19": {
  "hangul": "쁠록까",
  "roman": "plok.ka",
  "ko": "(뜻 없는 재잘 소리)",
  "en": "(babble)",
  "cat": "babble",
  "kw": []
 },
 "b20": {
  "hangul": "되뤽",
  "roman": "dö.lük",
  "ko": "(뜻 없는 재잘 소리)",
  "en": "(babble)",
  "cat": "babble",
  "kw": []
 },
 "b21": {
  "hangul": "뾸로",
  "roman": "pyol.lo",
  "ko": "(뜻 없는 재잘 소리)",
  "en": "(babble)",
  "cat": "babble",
  "kw": []
 },
 "b22": {
  "hangul": "뜨림발",
  "roman": "trim.bal",
  "ko": "(뜻 없는 재잘 소리)",
  "en": "(babble)",
  "cat": "babble",
  "kw": []
 },
 "b23": {
  "hangul": "플로삑",
  "roman": "flo.pik",
  "ko": "(뜻 없는 재잘 소리)",
  "en": "(babble)",
  "cat": "babble",
  "kw": []
 },
 "b24": {
  "hangul": "귈룸",
  "roman": "gül.lum",
  "ko": "(뜻 없는 재잘 소리)",
  "en": "(babble)",
  "cat": "babble",
  "kw": []
 },
 "b25": {
  "hangul": "브래뽐",
  "roman": "brae.pom",
  "ko": "(뜻 없는 재잘 소리)",
  "en": "(babble)",
  "cat": "babble",
  "kw": []
 },
 "b26": {
  "hangul": "뉙까롭",
  "roman": "nük.ka.lop",
  "ko": "(뜻 없는 재잘 소리)",
  "en": "(babble)",
  "cat": "babble",
  "kw": []
 },
 "b27": {
  "hangul": "돌블립",
  "roman": "dol.blip",
  "ko": "(뜻 없는 재잘 소리)",
  "en": "(babble)",
  "cat": "babble",
  "kw": []
 },
 "b28": {
  "hangul": "끌뢰밀",
  "roman": "klö.mil",
  "ko": "(뜻 없는 재잘 소리)",
  "en": "(babble)",
  "cat": "babble",
  "kw": []
 }
};
