"""Crop the game art the chat lab needs (portraits, emotes, a few UI icons) into small PNG data URIs.

Writes tools/chat_lab/gen/assets.js (an ES module) — run by tools/chat_lab/build.mjs.
Reads only: assets/villagers*/portrait_*.png, assets/characters/portrait_player.png,
assets/emotes/emotes.{png,json}, assets/fx_city/ui4_icons.{png,json}, assets/ui3/ui3_icons.{png,json}.
"""
import base64, io, json, os, sys
from PIL import Image

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
OUT = os.path.join(os.path.dirname(__file__), 'gen', 'assets.js')
LAB = ['npc_aunt', 'npc_kid_girl', 'npc_kid_prankster', 'npc_teen_girl', 'npc_uncle', 'npc_grandma', 'npc_clerk_a', 'npc_blacksmith']
EMOTES = ['heart', 'love', 'laugh', 'exclaim', 'question', 'sweat', 'music', 'zzz', 'idea', 'sparkle', 'cold', 'tear', 'star', 'wave', 'thumbs', 'anger', 'bread', 'fish', 'snowball']
ICONS = [('fx_city/ui4_icons', 'ui_icon_story', 'story'), ('fx_city/ui4_icons', 'ui_icon_rumor', 'rumor'), ('fx_city/ui4_icons', 'ui_icon_memory', 'memory'),
         ('fx_city/ui4_icons', 'ui_icon_newspaper', 'newspaper'), ('fx_city/ui4_icons', 'ui_icon_question', 'question'), ('fx_city/ui4_icons', 'ui_icon_friend_new', 'friend'),
         ('ui3/ui3_icons', 'ui_icon_day', 'day'), ('ui3/ui3_icons', 'ui_icon_night', 'night'), ('ui3/ui3_icons', 'ui_icon_request', 'request')]


def uri(im, size):
    im = im.convert('RGBA')
    im.thumbnail((size, size), Image.LANCZOS)
    q = im.quantize(colors=96, method=Image.FASTOCTREE)
    buf = io.BytesIO()
    q.save(buf, 'PNG', optimize=True)
    return 'data:image/png;base64,' + base64.b64encode(buf.getvalue()).decode('ascii')


def atlas(name):
    d = json.load(open(os.path.join(ROOT, 'assets', name + '.json')))
    fr = d.get('frames', d)
    if isinstance(fr, list):
        fr = {f['filename']: f for f in fr}
    return Image.open(os.path.join(ROOT, 'assets', name + '.png')).convert('RGBA'), fr


def crop(img, fr, key):
    f = fr[key]['frame']
    return img.crop((f['x'], f['y'], f['x'] + f['w'], f['y'] + f['h']))


def find_portrait(key):
    for d in ['villagers', 'villagers2', 'villagers3', 'characters', 'pets2']:
        p = os.path.join(ROOT, 'assets', d, 'portrait_' + key + '.png')
        if os.path.exists(p):
            return p
    return None


def main():
    out = {'portraits': {}, 'emotes': {}, 'icons': {}}
    for k in LAB + ['player']:
        p = find_portrait(k)
        if p:
            out['portraits'][k] = uri(Image.open(p), 112)
    try:
        em, fr = atlas('emotes/emotes')
        for e in EMOTES:
            if 'emote_' + e in fr:
                out['emotes'][e] = uri(crop(em, fr, 'emote_' + e), 48)
    except Exception as ex:  # art missing: the page falls back to no emote images
        print('emotes skipped:', ex, file=sys.stderr)
    cache = {}
    for sheet, frame, name in ICONS:
        try:
            if sheet not in cache:
                cache[sheet] = atlas(sheet)
            img, fr = cache[sheet]
            out['icons'][name] = uri(crop(img, fr, frame), 48)
        except Exception as ex:
            print('icon skipped:', name, ex, file=sys.stderr)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, 'w') as f:
        f.write('// generated by tools/chat_lab/make_assets.py — do not edit\nexport default ' + json.dumps(out) + ';\n')
    total = sum(len(v) for g in out.values() for v in g.values())
    print('assets: %d portraits, %d emotes, %d icons, %.1f KB' % (len(out['portraits']), len(out['emotes']), len(out['icons']), total / 1024))


if __name__ == '__main__':
    main()
