"""
civ_pack.py - turn the raw civic renders (civ_render.py cache) into assets/civic/: trimmed Phaser atlases (each sheet
<= 2048 px, palettised with libimagequant) + manifest.json, then the previews (civ_preview.py).

No Blender needed: python3 with numpy + Pillow (+ `imagequant`).
    python3 tools/blender/civ_pack.py [--cache DIR] [--quantize on|auto|off] [--no-previews] [--allow-partial]
                                      [--out DIR] [--prev DIR]        (dry runs: write somewhere else)

Guard + merge (like bld_pack / town_pack / veh_pack): the packer MERGES into the existing assets/civic/manifest.json
(unknown top-level fields and extra fields inside entries are kept, generated fields win) and REFUSES (exit 1, nothing
written) when a key of the current manifest or of civ_check.REQUIRED has no complete render in the cache, because
rebuilding the atlases would drop it.  --allow-partial packs what is cached.  An empty manifest is never written.

Steps
  1. plain builds: <cache>/<build>.json sidecars (bld_render format).  Shadow-caught frames get the village-building
     post (pack_utils.clean_alpha + prop_pack.tint_shadow + prop_pack.border_fade); fence tiles get a
     partition-of-unity cut of their (continuous) shadow instead of the border fade; overlay frames (ruin smoke) only
     clean_alpha.
  2. cutaway builds (bank, police_station): the ground-shadow pass is merged UNDER the floor layer; the closed
     building (<key>) is composited from all layers (overlays at frame 0); revealPoly = convex hull of the shell.
  3. vehicles: <cache>/<key>/meta.json + frames, the characters' 1 px ink outline (char_pack.ink_outline).
  4. scorch decals: generated by civ_decals.py (procedural, deterministic).
  5. atlases: civ_bank, civ_police, civ_ruins, civ_props, civ_moving, civ_demo, civ_decals (+ _2 .. at 2048 px; a
     build's frames always share a sheet), civ_excavator, civ_dump_truck.
  6. manifest: sprites{} + characters{} (vehicles) + fenceRings + demolitionLayout + fireSequence + conventions.
"""
import json
import math
import os
import sys
import tempfile
from collections import OrderedDict

import numpy as np
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
GAME = os.path.normpath(os.path.join(HERE, '..', '..'))
sys.path.insert(0, os.path.join(GAME, 'tools'))
sys.path.insert(0, HERE)
import pack_utils as pu  # noqa: E402
import prop_pack as pp   # noqa: E402  (read-only reuse: tint_shadow, border_fade)

ASSETS = os.path.join(GAME, 'assets')
OUT = os.path.join(ASSETS, 'civic')
PREV = os.path.join(GAME, 'docs', 'previews')
MAX_SHEET = 2048
BUDGET_MB = 7.0
ATLAS_ORDER = ['civ_bank', 'civ_police', 'civ_ruins', 'civ_smoke', 'civ_props', 'civ_moving', 'civ_demo', 'civ_decals']
RGBA_ATLASES = {'civ_smoke'}      # soft smoke alpha: keep 8-bit alpha (no palette speckle)
VEH_KEYS = ['excavator', 'dump_truck']
SQ2 = math.sqrt(2.0)
PX_X, PX_Y = 45.2548, 22.6274

POINT_SINGLE = {'door': 'doorPoint', 'entry': 'entryPoint', 'atm': 'atmPoint', 'vault': 'vaultPoint',
                'desk': 'deskPoint', 'celldoor': 'cellDoorPoint', 'cellseat': 'cellSeatPoint', 'carbay': 'carBayPoint',
                'sidedoor': 'sideDoorPoint', 'hose': 'hosePoint', 'drop': 'dropPoint'}
POINT_LIST = {'staff': 'staffPoints', 'customer': 'customerPoints', 'counter': 'counterPoints', 'seat': 'seatPoints',
              'cell': 'cellPoints', 'work': 'workPoints', 'gather': 'gatherPoints', 'poster': 'posterPoints'}
NO_DIR = {'poster', 'drop'}
SLOT = {'staffPoints': 'behind', 'cellPoints': 'behind', 'cellPoint': 'behind', 'cellSeatPoint': 'behind', 'vaultPoint': 'behind',
        'customerPoints': 'front', 'counterPoints': 'front', 'seatPoints': 'front', 'atmPoint': 'front',
        'entryPoint': 'front', 'deskPoint': 'front', 'cellDoorPoint': 'front', 'doorPoint': 'outside',
        'carBayPoint': 'outside', 'sideDoorPoint': 'outside'}


def dir_field(field):
    return field[:-6] + 'Dirs' if field.endswith('Points') else field[:-5] + 'Dir'


# --------------------------------------------------------------------------- post

def shadow_post(im):
    return pp.border_fade(pp.tint_shadow(pu.clean_alpha(im, floor=10)))


def tile_shadow_seg(img, anchor, axis, seg, h=0.14):
    """Partition-of-unity cut of the SHADOW pixels of a tile rendered with shadow-only neighbours (prop_pack.
    tile_shadow generalised to any segment length): w(u) + w(u - seg) = 1, a' = 1 - (1 - a)^w."""
    a = np.asarray(img.convert('RGBA')).astype(np.float32)
    H, W = a.shape[:2]
    ax, ay = anchor
    px, py = np.meshgrid(np.arange(W) + 0.5 - ax, np.arange(H) + 0.5 - ay)
    gx = (px / PX_X + py / PX_Y) / 2.0
    gy = (px / PX_X - py / PX_Y) / 2.0
    u = np.abs(gx if axis == 'x' else gy)
    w = np.clip(0.5 + (seg / 2.0 - u) / (2 * h), 0.0, 1.0)
    alpha = a[..., 3] / 255.0
    lum = a[..., :3].mean(-1)
    m = np.clip(1.0 - lum / 70.0, 0.0, 1.0) * (a[..., 3] < 252)
    new = 1.0 - np.power(np.clip(1.0 - alpha, 1e-6, 1.0), w)
    alpha = alpha * (1 - m) + new * m
    a[..., 3] = np.clip(alpha * 255.0, 0, 255)
    a[a[..., 3] < 1] = 0
    return Image.fromarray(a.astype(np.uint8), 'RGBA')


def load(cache):
    builds, vehicles = {}, {}
    if not os.path.isdir(cache):
        return builds, vehicles
    for fn in sorted(os.listdir(cache)):
        p = os.path.join(cache, fn)
        if os.path.isdir(p) and os.path.exists(os.path.join(p, 'meta.json')):
            m = json.load(open(os.path.join(p, 'meta.json')))
            names = ['%s_%s_%d' % (a, d, i) for a, info in m['anims'].items() for d in m['dirs']
                     for i in range(info['frames'])]
            co = m.get('cargoOverlay')
            if co:
                names += ['cargo_%s_%s_%d' % (a, d, i) for a in co['anims'] for d in m['dirs']
                          for i in range(co['frames'][a])]
            if all(os.path.exists(os.path.join(p, n + '.png')) for n in names):
                m['names'] = names
                vehicles[fn] = m
            else:
                print('note: vehicle %s has missing frames - not packed' % fn)
        elif fn.endswith('.json'):
            try:
                m = json.load(open(p))
            except Exception:
                continue
            if 'build' not in m or 'frames' not in m:
                continue
            need = list(m['frames']) + [f for ov in m.get('overlays', {}).values() for f in ov['frames']]
            if all(os.path.exists(os.path.join(cache, n + '.png')) for n in need):
                builds[m['build']] = m
            else:
                print('note: %s has missing frames - not packed' % m['build'])
    return builds, vehicles


def build_images(cache, m):
    """{frame name -> post-processed RGBA} for one build (cutaway: + the composited closed frame)."""
    key = m['build']
    out = {}

    def raw(n):
        return Image.open(os.path.join(cache, n + '.png')).convert('RGBA')
    if m.get('cutaway'):
        ground = shadow_post(raw(m['cutaway']['ground']))
        layers = {}
        for lay in m['cutaway']['layers']:
            layers[lay] = pu.clean_alpha(raw('%s_%s' % (key, lay)), floor=3)
        floor = ground.copy()
        if 'floor' in layers:
            floor.alpha_composite(layers['floor'])
        layers['floor'] = floor
        for lay, im in layers.items():
            out['%s_%s' % (key, lay)] = im
        ov_imgs = {}
        for name, ov in m.get('overlays', {}).items():
            for f in ov['frames']:
                ov_imgs[f] = pu.clean_alpha(raw(f), floor=3)
                out[f] = ov_imgs[f]
        closed = floor.copy()
        for lay in draw_layers(m):
            if lay.startswith('@'):
                continue
            if lay in m.get('overlays', {}):
                closed.alpha_composite(ov_imgs[m['overlays'][lay]['frames'][0]])
            elif lay != 'floor' and lay in layers and lay != 'shell_cut':
                closed.alpha_composite(layers[lay])
        out[key] = closed
        return out
    tile = m.get('tileAxis')
    for n in m['frames']:
        im = raw(n)
        if not m.get('shadow', True):
            im = pu.clean_alpha(im, floor=3)
        elif tile:
            im = pp.tint_shadow(tile_shadow_seg(pu.clean_alpha(im, floor=10), m['anchorPx'], tile, m['segM']))
        else:
            im = shadow_post(im)
        out[n] = im
    for name, ov in m.get('overlays', {}).items():
        for f in ov['frames']:
            out[f] = smooth_smoke(pu.clean_alpha(raw(f), floor=3)) if name == 'smoke' else pu.clean_alpha(raw(f), floor=3)
    return out


def smooth_smoke(im, radius=1.3):
    """Polish v2: Cycles leaves the soft smoke's ALPHA speckled (the denoiser only cleans colour).  Blur the frame in
    premultiplied space, but keep the original pixels where they are (nearly) opaque - the embers and the crisp
    edges where a wall cuts the wisp stay sharp."""
    from PIL import ImageFilter
    a = np.asarray(im).astype(np.float32) / 255.0
    pre = np.dstack([a[..., :3] * a[..., 3:4], a[..., 3:4]])
    chans = [np.asarray(Image.fromarray((pre[..., i] * 255).astype(np.uint8)).filter(
        ImageFilter.GaussianBlur(radius))).astype(np.float32) / 255.0 for i in range(4)]
    bl = np.dstack(chans)
    alpha = bl[..., 3:4]
    rgb = np.where(alpha > 1e-4, bl[..., :3] / np.maximum(alpha, 1e-4), 0.0)
    keep = (a[..., 3:4] > 0.8).astype(np.float32)
    out_rgb = rgb * (1 - keep) + a[..., :3] * keep
    out_a = alpha * (1 - keep) + a[..., 3:4] * keep
    res = np.dstack([out_rgb, out_a])
    res = np.clip(res * 255.0 + 0.5, 0, 255).astype(np.uint8)
    res[res[..., 3] < 2] = 0
    return Image.fromarray(res, 'RGBA')


def draw_layers(m):
    """Game draw order for a cutaway build: layer names + '@behind' / '@front' character slots."""
    order = ['floor', 'back', 'interior', '@behind', 'front', '@front', 'shell_cut', 'shell']
    for name, ov in m.get('overlays', {}).items():
        after = ov.get('drawAfter', 'interior')
        idx = order.index('interior') + 1 if after == 'interior' else order.index('front') + 1
        order.insert(idx, name)
    return [x for x in order if x.startswith('@') or x in m['cutaway']['layers'] or x in m.get('overlays', {})]


def centre_anchor(m):
    """Polish v2: pad every frame of a vehicle symmetrically so the anchor x is EXACTLY the frame centre (ax = 0.5).
    Phaser mirrors a flipped frame around the frame centre (Sprite.setFlipX with setOrigin(anchor), as Train.js
    does), so an off-centre anchor would shift a mirrored SW / NW vehicle sideways (excavator 42 px).  The padding is
    trimmed away in the atlas (no memory) and every point stays an offset from the anchor (unchanged).
    Returns (pad_left, pad_right)."""
    W, H = m['frameSize']
    ax, ay = m['anchorPx']
    left, right = ax, W - ax
    pl, pr = max(0, right - left), max(0, left - right)
    m['frameSize'] = [W + pl + pr, H]
    m['anchorPx'] = [ax + pl, ay]
    m['anchor'] = [0.5, round(ay / float(H), 5)]
    m['anchorPad'] = [pl, pr]
    return pl, pr


def veh_images(cache, key, m):
    import char_pack as cp      # read-only reuse of the characters' ink outline
    pl, pr = m.get('anchorPad') or centre_anchor(m)
    out = {}
    for n in m['names']:
        im = cp.ink_outline(Image.open(os.path.join(cache, key, n + '.png')))
        if pl or pr:
            big = Image.new('RGBA', (im.width + pl + pr, im.height), (0, 0, 0, 0))
            big.paste(im, (pl, 0))
            im = big
        out[n] = im
    return out


# --------------------------------------------------------------------------- manifest helpers

def footprint_poly(m):
    fm = m.get('footprintM')
    if not isinstance(fm, list) or len(fm) != 2:
        return None
    a, b = fm
    yaw = math.radians(m.get('yaw', 0.0))
    pts = []
    for lx, ly in ((-a / 2, -b / 2), (a / 2, -b / 2), (a / 2, b / 2), (-a / 2, b / 2)):
        x = lx * math.cos(yaw) - ly * math.sin(yaw)
        y = lx * math.sin(yaw) + ly * math.cos(yaw)
        pts.append([int(round((x + y) * PX_X)), int(round((x - y) * PX_Y))])
    return pts


def hull(points):
    pts = sorted(set(points))
    if len(pts) < 3:
        return pts

    def cross(o, a, b):
        return (a[0] - o[0]) * (b[1] - o[1]) - (a[1] - o[1]) * (b[0] - o[0])
    lo, up = [], []
    for p in pts:
        while len(lo) >= 2 and cross(lo[-2], lo[-1], p) <= 0:
            lo.pop()
        lo.append(p)
    for p in reversed(pts):
        while len(up) >= 2 and cross(up[-2], up[-1], p) <= 0:
            up.pop()
        up.append(p)
    return lo[:-1] + up[:-1]


def simplify(poly, n=10):
    poly = list(poly)
    while len(poly) > n:
        best, bi = None, 0
        for i in range(len(poly)):
            a, b, c = poly[i - 1], poly[i], poly[(i + 1) % len(poly)]
            area = abs((b[0] - a[0]) * (c[1] - a[1]) - (c[0] - a[0]) * (b[1] - a[1]))
            if best is None or area < best:
                best, bi = area, i
        poly.pop(bi)
    return poly


def reveal_poly(img, anchor):
    a = np.asarray(img)[..., 3]
    ys, xs = np.nonzero(a > 140)
    if not len(xs):
        return []
    # boundary samples: per row extremes
    pts = []
    for y in np.unique(ys)[::2]:
        row = xs[ys == y]
        pts += [(int(row.min()), int(y)), (int(row.max()), int(y))]
    poly = simplify(hull(pts), 10)
    return [[int(x - anchor[0]), int(y - anchor[1])] for x, y in poly]


def put_points(s, pts, dirs):
    for kind, field in POINT_SINGLE.items():
        if pts.get(kind):
            s[field] = pts[kind][0]
            if dirs.get(kind) and kind not in NO_DIR:
                s[dir_field(field)] = dirs[kind][0]
    for kind, field in POINT_LIST.items():
        if pts.get(kind):
            s[field] = pts[kind]
            if dirs.get(kind) and kind not in NO_DIR:
                s[dir_field(field)] = dirs[kind]


def base_entry(m, frame, atlas):
    s = {'atlas': atlas, 'frame': frame, 'anchor': m['anchor'], 'frameSize': m['frameSize'], 'kind': m['kind']}
    if 'footprint' in m:
        s['footprint'] = m['footprint']
        s['footprintM'] = m['footprintM']
    poly = footprint_poly(m)
    if poly and not m.get('tileAxis'):
        s['footprintPoly'] = poly
    tops = m.get('topPx', {})
    s['topPx'] = tops.get(frame, next(iter(tops.values()))) if isinstance(tops, dict) and tops else tops
    if m.get('front'):
        s['front'] = m['front']
    for f in ('name', 'zone'):
        if f in m:
            s[f] = m[f]
    return s


def entries_for(k, m, fa):
    """Manifest sprite entries for one build: {sprite key -> entry}."""
    out = {}
    if m.get('cutaway'):
        s = base_entry(m, k, fa[k])
        s['kind'] = 'building'
        pts = m['framePoints'][k]
        dirs = m['frameDirs'][k]
        put_points(s, pts, dirs)
        if s.get('cellPoints') and 'cellPoint' not in s:      # contract name (CONTRACT_V8 AB): the jail cell spot
            s['cellPoint'] = s['cellPoints'][0]
            if s.get('cellDirs'):
                s['cellDir'] = s['cellDirs'][0]
        s['pointSlots'] = {f: SLOT[f] for f in SLOT if f in s}
        if m.get('fxPoints'):
            s['fxPoints'] = m['fxPoints']
        lay_keys = {lay: '%s_%s' % (k, lay) for lay in m['cutaway']['layers']}
        order = []
        for lay in draw_layers(m):
            order.append(lay if lay.startswith('@') else ('%s_%s' % (k, lay)))
        ovs = {}
        for name, ov in m.get('overlays', {}).items():
            an = ov.get('name', name)
            rev = ov.get('reverse', an + '_close')
            ovs['%s_%s' % (k, name)] = {'anims': [an, rev], 'drawAfter': ov.get('drawAfter', 'interior'),
                                        'frames': len(ov['frames'])}
        s['cutaway'] = {
            'layers': lay_keys, 'drawOrder': order, 'overlays': ovs,
            'fade': {'layer': lay_keys.get('shell'), 'closedAlpha': 1.0, 'openAlpha': 0.12, 'ms': 260},
            'cut': {'layer': lay_keys.get('shell_cut'), 'visible': 'only while revealed (fade in with the shell fade out)'},
            'revealPoly': m.get('revealPoly', []),
            'floorLiftPx': m.get('floorLiftPx', 0),
            'notes': ('Draw every layer at the SAME position + origin (anchor) as the building. Depth: base = anchor y; '
                      'layers / slots in drawOrder get base + 0.01 * index (characters inside: base + slot offset + '
                      'their own y * 1e-4 for sorting among themselves). Closed: draw the plain <key> frame (or all '
                      'layers - identical). Reveal (tap / hover inside revealPoly, or the chief walks in): fade the '
                      'shell to openAlpha and show shell_cut; residents inside are only drawn while revealed '
                      '(or always - the closed shell covers them). Characters at pointSlots "behind" go to @behind, '
                      '"front" to @front; outside points use normal y-sorting.'),
        }
        s['revealPoly'] = m.get('revealPoly', [])
        if m.get('notes'):
            s['notes'] = m['notes']
        out[k] = s
        for lay, lk in lay_keys.items():
            e = base_entry(m, lk, fa[lk])
            e['kind'] = 'layer'
            e['layerOf'] = k
            e['layer'] = lay
            out[lk] = e
        for name, ov in m.get('overlays', {}).items():
            ok = '%s_%s' % (k, name)
            e = base_entry(m, ov['frames'][0], fa[ov['frames'][0]])
            e['kind'] = 'layer'
            e['layerOf'] = k
            e['layer'] = name
            an = ov.get('name', name)
            rev = ov.get('reverse', an + '_close')
            e['anims'] = {an: {'frames': list(ov['frames']), 'fps': ov['fps'], 'repeat': 0},
                          rev: {'frames': list(reversed(ov['frames'])), 'fps': ov['fps'], 'repeat': 0}}
            e['drawAfter'] = ov.get('drawAfter', 'interior')
            e['notes'] = ('Animated overlay of %s (same frame + anchor as the building, trimmed in the atlas). Frame 0 '
                          '= closed. Play %s to open, %s to close; it stays on the last frame.' % (k, an, rev))
            out[ok] = e
        return out
    sprites = m.get('sprites') or {k: {'frame': k}}
    for sk, sd in sprites.items():
        fr = sd['frame']
        s = base_entry(m, fr, fa[fr])
        pts = m.get('framePoints', {}).get(fr, {})
        dirs = m.get('frameDirs', {}).get(fr, {})
        put_points(s, pts, dirs)
        if 'stage' in sd:
            s['stage'] = sd['stage']
            s['stages'] = list(sprites)
        if m.get('fxPoints'):
            s['fxPoints'] = {n: v for n, v in m['fxPoints'].items() if v is not None}
        if 'anims' in m and sk == k:
            w = dict(m['anims']['work'])
            s['anims'] = {'work': w}
            if m.get('anim_name') or m.get('animAlias'):
                s['anims'][m.get('anim_name') or m.get('animAlias')] = dict(w)
        for f in ('tileAxis', 'segM', 'stepPx', 'postEnd', 'tileLayer', 'posterSizePx', 'posterNote', 'boardPx'):
            if f in m:
                s[f] = m[f]
        if m.get('notes'):
            s['notes'] = m['notes']
        out[sk] = s
    for name, ov in m.get('overlays', {}).items():
        ok = '%s_%s' % (k, name)
        e = base_entry(m, ov['frames'][0], fa[ov['frames'][0]])
        e['kind'] = 'overlay'
        e['of'] = k
        e['anims'] = {name: {'frames': list(ov['frames']), 'fps': ov['fps'], 'repeat': ov['repeat']}}
        e['notes'] = ('Smoke wisps of %s: draw this sprite on top of %s at the same position (same frame size + '
                      'anchor) and play spr:%s:%s while the ruin smoulders.' % (k, k, ok, name))
        out[ok] = e
    return out


def veh_entry(k, m, atlas_key):
    import veh_pack as vp       # read-only reuse: the vehicles' manifest entry (shadow ellipse, points, seats ...)
    e = vp.veh_entry(k, m, atlas_key, None)
    e.pop('overlay', None)
    for a, info in m['anims'].items():
        for f in ('digFrame', 'dumpFrame', 'tipFrame', 'pileFrame'):
            if f in info:
                e['anims'][a][f] = info[f]
    for f in ('cargoGround', 'tipPoint', 'dumpPoint', 'digPoint', 'framePoints', 'cargoOverlay'):
        if f in m:
            e[f] = m[f]
    fp = m.get('framePoints', {})
    if 'bucketPoints' in fp:            # contract name (CONTRACT_V8 AB): bucketPoint[anim][dir][frame] = px offset
        e['bucketPoint'] = fp['bucketPoints']
    if 'bedPoints' in fp:
        e['bedPoint'] = fp['bedPoints']
    if 'crew' in m:
        e['crew'] = m['crew']
    return e


# --------------------------------------------------------------------------- layouts

def iso(x, y, z=0.0):
    return [int(round((x + y) * PX_X)), int(round((x - y) * PX_Y - z * 55.4256))]


def fence_rings():
    """Ready-made demolition fence rings around S / M / L plots: n tiles of sqrt(2) m per side (2 / 3 / 4), offsets
    in px from the plot centre (= the ruin / site anchor).  Back edges first (draw order = y-sort anyway)."""
    out = {}
    for sz, n in (('S', 2), ('M', 3), ('L', 4)):
        h = n * SQ2 / 2
        ring = []
        for k in range(n):
            c = -h + SQ2 / 2 + k * SQ2
            ring.append({'key': 'demolition_fence_x' + ('_lamp' if k == n // 2 else ''), 'at': iso(c, h)})
            ring.append({'key': 'demolition_fence_y', 'at': iso(-h, c)})
            ring.append({'key': 'demolition_fence_y' + ('_lamp' if k == n // 2 else ''), 'at': iso(h, c)})
            ring.append({'key': 'demolition_fence_x', 'at': iso(c, -h)})
        ring.append({'key': 'demolition_fence_post', 'at': iso(h, h)})
        out[sz] = {'sideM': round(n * SQ2, 3), 'tilesPerSide': n, 'pieces': ring,
                   'gate': 'leave out one front demolition_fence_x piece for a walk-in gap'}
    return out


def to_world(dx, dy):
    return (dx / PX_X + dy / PX_Y) / 2.0, (dx / PX_X - dy / PX_Y) / 2.0


MIRROR_OF = {'SW': 'SE', 'NW': 'NE'}
SIDES = OrderedDict([            # street side of the plot -> (inward unit vector u, excavator heading)
    ('Y-', ((0.0, 1.0), 'NE')),    # front-left (screen down-left)  - the default: building fronts face -Y
    ('X+', ((-1.0, 0.0), 'NW')),   # front-right (screen down-right) - mirror of Y-
    ('X-', ((1.0, 0.0), 'SE')),    # back-left: the ruin hides the bite (digVisible false)
    ('Y+', ((0.0, -1.0), 'SW')),   # back-right: mirror of X-
])
TRUCK_DIRS = {'NE': ('SW', 'NE'), 'NW': ('SE', 'NW'), 'SE': ('NW', 'SE'), 'SW': ('NE', 'SW')}
PLOT_HALF = {'S': (1.0, 1.0), 'M': (1.5, 1.5), 'L': (2.0, 2.0)}


def dir_pt(by_dir, d):
    if d in by_dir:
        return list(by_dir[d][:2])
    p = by_dir[MIRROR_OF[d]]
    return [-p[0], p[1]]


def dir_poly(by_dir, d):
    if d in by_dir:
        return [list(p) for p in by_dir[d]]
    return [[-p[0], p[1]] for p in by_dir[MIRROR_OF[d]]]


def poly_world(at_px, poly_px):
    ox, oy = to_world(*at_px)
    return [(ox + to_world(*p)[0], oy + to_world(*p)[1]) for p in poly_px]


def sat_gap(a, b):
    """Separation distance between two convex polygons (0 if they overlap) along their edge normals."""
    best = -1e9
    for poly in (a, b):
        n = len(poly)
        for i in range(n):
            x0, y0 = poly[i]
            x1, y1 = poly[(i + 1) % n]
            nx, ny = y1 - y0, -(x1 - x0)
            ln = math.hypot(nx, ny) or 1.0
            nx, ny = nx / ln, ny / ln
            pa = [x * nx + y * ny for x, y in a]
            pb = [x * nx + y * ny for x, y in b]
            gap = max(min(pb) - max(pa), min(pa) - max(pb))
            best = max(best, gap)
    return max(0.0, best)


def square(h):
    return [(-h, -h), (h, -h), (h, h), (-h, h)]


def sprite_alpha(img, anchor, at, px):
    """alpha of a sprite drawn with its anchor at `at` (px, plot space) at plot-space pixel px (0 outside)."""
    x = int(round(px[0] - at[0] + anchor[0]))
    y = int(round(px[1] - at[1] + anchor[1]))
    if 0 <= x < img.width and 0 <= y < img.height:
        return img.getpixel((x, y))[3]
    return 0


def covered_fraction(target, others):
    """Fraction of the opaque pixels of target (img, anchor, at) covered by opaque pixels of the others drawn on top."""
    img, anc, at = target
    a = np.asarray(img)[..., 3] > 128
    ys, xs = np.nonzero(a)
    if not len(xs):
        return 0.0
    cov = np.zeros(len(xs), bool)
    for oimg, oanc, oat in others:
        oa = np.asarray(oimg)[..., 3] > 128
        ox = xs + int(round(- anc[0] + at[0] - oat[0] + oanc[0]))
        oy = ys + int(round(- anc[1] + at[1] - oat[1] + oanc[1]))
        ok = (ox >= 0) & (ox < oimg.width) & (oy >= 0) & (oy < oimg.height)
        hit = np.zeros(len(xs), bool)
        hit[ok] = oa[oy[ok], ox[ok]]
        cov |= hit
    return float(cov.mean())


def demolition_layout(vehicles, vimgs=None, frames=None, builds=None):
    """Polish v2 - where the excavator and the dump truck stand while clearing an S / M / L plot, for each street
    side of the plot (px offsets from the plot centre = the ruin / site anchor):
      * the excavator stands OUTSIDE the fence ring on the street side, heading into the plot, so it is drawn in
        front of the ruin and its bucket bites the ruin's front at digFrame (front sides Y- / X+);
      * it swings LEFT (away from the camera) to dump, so the dump truck parks BEHIND it (never hides it), with its
        cargoGround under the excavator's dumpPoint, >= 0.5 m clear of the fence ring and of the excavator;
      * gateIndex = a fence piece (fenceRings[size].pieces index) on a camera-facing side that no vehicle blocks -
        leave it out so the crew / chief can walk in.
    The search runs in world metres (convex footprints, separating axes); the best few candidates are then checked
    in screen space with the real sprites: the bucket at digFrame must not be covered by anything drawn after the
    excavator (front sides), and the truck must not cover more than 30 % of the excavator."""
    exc, dump = vehicles.get('excavator'), vehicles.get('dump_truck')
    if not exc or not dump:
        return {}
    rings = fence_rings()
    dig_f = exc['anims']['dig'].get('digFrame', 2)
    out = OrderedDict()
    for sz, n in (('S', 2), ('M', 3), ('L', 4)):
        h = n * SQ2 / 2
        ph = PLOT_HALF[sz][0]
        fence = square(h + 0.06)
        ruin_key = 'ruin_%s' % sz.lower()
        per = OrderedDict()
        for side, (u, edir) in SIDES.items():
            w = (-u[1], u[0])
            epoly = dir_poly(exc['footprintPoly'], edir)
            dig = dir_pt(exc['digPoint'], edir)
            dump_p = dir_pt(exc['dumpPoint'], edir)
            cands = []
            for di in range(0, 80):
                d_ = h + 0.4 + di * 0.05
                for li in range(-60, 61):
                    l_ = li * 0.05
                    E = (-u[0] * d_ + w[0] * l_, -u[1] * d_ + w[1] * l_)
                    E_px = iso(*E)
                    ep = poly_world(E_px, epoly)
                    if sat_gap(ep, fence) < 0.12:
                        continue
                    gx, gy = to_world(E_px[0] + dig[0], E_px[1] + dig[1])
                    if abs(gx) > ph - 0.15 or abs(gy) > ph - 0.15:
                        continue
                    depth = (gx * u[0] + gy * u[1]) + ph          # from the street edge of the plot
                    lat = gx * w[0] + gy * w[1]
                    for tdir in TRUCK_DIRS[edir]:
                        cg = dir_pt(dump['cargoGround'], tdir)
                        T_px = [E_px[0] + dump_p[0] - cg[0], E_px[1] + dump_p[1] - cg[1]]
                        tp = poly_world(T_px, dir_poly(dump['footprintPoly'], tdir))
                        if sat_gap(tp, fence) < 0.5 or sat_gap(tp, ep) < 0.25:
                            continue
                        score = abs(depth - 0.32 * 2 * ph) * 3.0 + abs(lat) * 1.0 + d_ * 0.2 + \
                            (0.0 if tdir in ('SW', 'SE') else 0.35)     # prefer the truck's cab toward the camera
                        cands.append((score, E_px, edir, T_px, tdir, (round(gx, 2), round(gy, 2))))
            cands.sort(key=lambda c: c[0])
            pick, checks = None, {}
            for c in cands[:400]:
                _, E_px, ed, T_px, td, dg = c
                ck = layout_pixels(E_px, ed, T_px, td, exc, dump, vimgs, frames, builds, rings[sz], dig_f, ruin_key)
                if ck is None or (ck['truckCoversExcavator'] <= 0.3 and (side in ('X-', 'Y+') or ck['digVisible'])):
                    pick, checks = c, ck or {}
                    break
            if pick is None and cands:
                pick = cands[0]
                checks = layout_pixels(pick[1], pick[2], pick[3], pick[4], exc, dump, vimgs, frames, builds,
                                       rings[sz], dig_f, ruin_key) or {}
                print('WARNING: demolitionLayout %s %s: no candidate passed the screen checks' % (sz, side))
            if pick is None:
                print('WARNING: demolitionLayout %s %s: no clear spot' % (sz, side))
                continue
            _, E_px, ed, T_px, td, dg = pick
            ew, tw = to_world(*E_px), to_world(*T_px)
            gate = gate_piece(rings[sz], h, side, [poly_world(E_px, epoly),
                                                   poly_world(T_px, dir_poly(dump['footprintPoly'], td))])
            e = OrderedDict()
            e['excavator'] = {'at': E_px, 'dir': ed, 'anim': 'dig', 'worldM': [round(ew[0], 2), round(ew[1], 2)],
                              'digPointWorldM': list(dg),
                              'notes': 'outside the fence on the %s side, heading into the plot; drawn in front of '
                                       'the ruin (y-sort by anchor)' % side}
            e['dump_truck'] = {'at': T_px, 'dir': td, 'worldM': [round(tw[0], 2), round(tw[1], 2)],
                               'anim': 'idle -> idle_loaded after the excavator\'s dumpFrame; move_loaded to leave',
                               'notes': 'behind the excavator (its left side, away from the camera), bed under the '
                                        'bucket at dumpFrame'}
            e['gateIndex'] = gate
            e['digVisible'] = bool(checks.get('digVisible', side in ('Y-', 'X+')))
            e['checks'] = checks
            per[side] = e
        lay = OrderedDict([('default', 'Y-'), ('sides', per)])
        if 'Y-' in per:                                    # backwards-compatible flat fields (= the default side)
            lay['excavator'] = per['Y-']['excavator']
            lay['dump_truck'] = per['Y-']['dump_truck']
            lay['gateIndex'] = per['Y-']['gateIndex']
        out[sz] = lay
    return out


def gate_piece(ring, h, side, vehicle_polys):
    """Index of a fence piece on a camera-facing side (-Y row or +X row) whose walk-in strip (1 m deep, outside the
    ring) no vehicle touches; nearest the front corner first."""
    best = None
    for i, pc in enumerate(ring['pieces']):
        if pc['key'] == 'demolition_fence_post':
            continue
        cx, cy = to_world(*pc['at'])
        if abs(cy + h) < 0.05:                              # -Y row (x tiles)
            strip = [(cx - 0.5, cy - 1.0), (cx + 0.5, cy - 1.0), (cx + 0.5, cy), (cx - 0.5, cy)]
            corner = abs(cx - h)
        elif abs(cx - h) < 0.05:                            # +X row (y tiles)
            strip = [(cx, cy - 0.5), (cx + 1.0, cy - 0.5), (cx + 1.0, cy + 0.5), (cx, cy + 0.5)]
            corner = abs(cy + h)
        else:
            continue
        if any(sat_gap(strip, vp) < 0.05 for vp in vehicle_polys):
            continue
        pref = 0 if (side in ('Y-', 'X-') and abs(cx - h) < 0.05) or (side in ('X+', 'Y+') and abs(cy + h) < 0.05) \
            else 1
        key = (pref, corner)
        if best is None or key < best[0]:
            best = (key, i)
    return best[1] if best else None


def sprite_frame(builds, frames, key):
    """(image, anchorPx) of a plain-build sprite key (fence tiles, ruins) or None."""
    for bk, m in builds.items():
        sps = m.get('sprites') or {bk: {'frame': m['frames'][0]}}
        if key in sps and sps[key]['frame'] in frames:
            return frames[sps[key]['frame']], m['anchorPx']
    return None


def layout_pixels(E_px, ed, T_px, td, exc, dump, vimgs, frames, builds, ring, dig_f, ruin_key):
    """Screen-space checks of one candidate with the real sprites (None if the images are not available)."""
    if not vimgs or 'excavator' not in vimgs or 'dump_truck' not in vimgs or not frames or not builds:
        return None

    def vframe(key, anim, d, i):
        src = d if d in ('SE', 'NE') else MIRROR_OF[d]
        im = vimgs[key]['%s_%s_%d' % (anim, src, i)]
        if src != d:
            im = im.transpose(Image.FLIP_LEFT_RIGHT)
        return im
    exc_img = vframe('excavator', 'dig', ed, dig_f)
    truck_img = vframe('dump_truck', 'idle', td, 0)
    ea = (exc_img.width / 2.0, exc['anchorPx'][1])
    da = (truck_img.width / 2.0, dump['anchorPx'][1])
    items = []
    for pc in ring['pieces']:
        sf = sprite_frame(builds, frames, pc['key'])
        if sf:
            items.append((sf[0], sf[1], pc['at']))
    sf = sprite_frame(builds, frames, ruin_key)
    if sf:
        items.append((sf[0], sf[1], [0, 0]))
    items.append((truck_img, da, T_px))
    later = [it for it in items if it[2][1] > E_px[1]]
    bp = exc['framePoints']['bucketPoints']['dig']
    b = dir_pt({d: v[dig_f] for d, v in bp.items()}, ed)
    P = (E_px[0] + b[0], E_px[1] + b[1])
    hits = 0
    for dx in (-3, 0, 3):
        for dy in (-3, 0, 3):
            if any(sprite_alpha(im, an, at, (P[0] + dx, P[1] + dy)) > 128 for im, an, at in later):
                hits += 1
    cover = covered_fraction((exc_img, ea, E_px), [(truck_img, da, T_px)]) if T_px[1] > E_px[1] else 0.0
    truck_vis = 1.0 - (covered_fraction((truck_img, da, T_px), [(exc_img, ea, E_px)]) if E_px[1] > T_px[1] else 0.0)
    return {'digVisible': hits <= 2, 'bucketCoveredSamples': hits, 'truckCoversExcavator': round(cover, 3),
            'truckVisible': round(truck_vis, 3)}


FIRE_SEQUENCE = [
    {'step': 'burning', 'draw': 'the building + fx_city fx_fire_bld_<s|m|l> / fx_smoke_column (fx_city fragment)'},
    {'step': 'ruin', 'draw': 'scorch_decal_<size> (ground) + ruinFor[building] at the building\'s anchor (ruin_s / '
                             'ruin_m / ruin_l on village plots, ruin_house_town / ruin_shop_town / ruin_l_town on town '
                             'lots) + its <ruin>_smoke overlay (smoke wisps + flickering embers) while it smoulders; '
                             'insurance_sign nearby. Remove the overlay when it has cooled: the base ruin is cold.'},
    {'step': 'demolition', 'draw': 'fenceRings[ring] without the gateIndex piece + excavator (dig) + dump_truck at '
                                   'demolitionLayout[ring].sides[street side] (default Y-); ruin -> rubble_pile_<size> '
                                   'when the excavator has knocked it down'},
    {'step': 'clearing', 'draw': 'rubble_pile_<size> -> rubble_pile_<size>_half -> nothing (dump truck leaves '
                                 'move_loaded and plays tip at the dump); scorch decal stays'},
    {'step': 'rebuild', 'draw': 'assets/buildings site_plot_<S|M|L> -> site_foundation -> site_scaffold (same anchor); '
                                'remove the fence; fade the scorch decal'},
    {'step': 'done', 'draw': 'the new building (same anchor)'},
]

# building key -> ruin / scorch / rubble / fence ring (polish v2: town buildings get town ruins, not a log cabin)
RUIN_FOR = OrderedDict()
for _k in ('house_a', 'house_b', 'house_c', 'watchtower'):
    RUIN_FOR[_k] = {'ruin': 'ruin_s', 'scorch': 'scorch_decal_s', 'rubble': 'rubble_pile_s', 'ring': 'S'}
for _k in ('warehouse', 'shop_general', 'boathouse'):
    RUIN_FOR[_k] = {'ruin': 'ruin_m', 'scorch': 'scorch_decal_m', 'rubble': 'rubble_pile_m', 'ring': 'M'}
for _k in ('townhouse_a', 'townhouse_b', 'townhouse_c', 'townhouse_d', 'police_box'):
    RUIN_FOR[_k] = {'ruin': 'ruin_house_town', 'scorch': 'scorch_decal_m', 'rubble': 'rubble_pile_s', 'ring': 'S'}
for _k in ('cafe', 'bookstore', 'clothing_store', 'flower_shop', 'hair_salon', 'toy_shop', 'hardware_store',
           'restaurant', 'carpenter_workshop', 'post_office'):
    RUIN_FOR[_k] = {'ruin': 'ruin_shop_town', 'scorch': 'scorch_decal_m', 'rubble': 'rubble_pile_m', 'ring': 'M'}
for _k in ('supermarket', 'apartment_a', 'apartment_b', 'clinic', 'fire_station'):
    RUIN_FOR[_k] = {'ruin': 'ruin_l_town', 'scorch': 'scorch_decal_l', 'rubble': 'rubble_pile_l', 'ring': 'L'}
RUIN_FOR['*'] = {'note': 'any other building: site_plot size S / M / L -> ruin_s / ruin_m / ruin_l (village) or the '
                         'town ruin whose footprint covers it; the bank, police station, school, town hall and train '
                         'station never burn down'}


CONVENTIONS = {
    'ppu': 64,
    'anchor': 'normalised [ax, ay] of the full untrimmed frame = world origin = footprint centre (vehicles: ground '
              'centre). Ruins / rubble / scorch decals share the anchor of the S / M / L plot (site_*) they sit on.',
    'points': 'every *Point(s) value is a px offset [dx, dy] from the anchor (unscaled); *Dir(s) = facing of a '
              'character standing there (SW / W / NW = flipped SE / E / NE frames). Points inside a cutaway building '
              'include the raised floor (floorLiftPx).',
    'cutaway': 'bank + police_station: see sprites[key].cutaway - aligned layers (_floor, _back, _interior, _front, '
               '_shell_cut, _shell) + animated overlay layers, all with the building\'s frame + anchor (trimmed in the '
               'atlas). drawOrder lists layers and the two character slots @behind (staff behind counters, the '
               'prisoner in the cell) and @front (customers, visitors). Fade _shell to reveal the inside, show '
               '_shell_cut (dollhouse wall stubs) while revealed. revealPoly = px polygon (anchor-relative) of the '
               'building silhouette for tap / hover tests.',
    'shadows': 'buildings / props have a baked soft cool shadow falling screen down-right (the cutaway ground shadow '
               'lives in _floor); vehicles none (use characters[key].shadow ellipse).',
    'overlays': '<ruin>_smoke: draw on top of the ruin at the same position, play its smoke anim (4 f loop) - smoke '
                'wisps + flickering embers (the base ruin frame is cold; remove the overlay once it has cooled). '
                'Packed RGBA (atlas civ_smoke) so the soft alpha has no palette speckle.',
    'flip': 'excavator + dump_truck frames are padded so anchor x == 0.5 exactly: setOrigin(anchor) + setFlipX(true) '
            'mirrors a SW / NW vehicle around its anchor (no sideways jump); mirror every point by negating dx.',
    'tiles': 'demolition_fence_x / _y: one tile = sqrt(2) m, step (64, 32) / (64, -32) px; the tile owns the post at '
             'its -axis end; shadows join seamlessly; close chains with demolition_fence_post. fenceRings = rings '
             'around S / M / L plots.',
    'decals': 'scorch_decal_* and welcome_mat are ground-layer decals (draw under everything standing on them).',
    'vehicles': 'characters{} kind "vehicle" (assets/vehicles conventions): rendered dirs SE (world +X) and NE '
                '(world +Y), mirror SW <- SE, NW <- NE, frame names {anim}_{dir}_{i}; an operator is baked into each '
                'cab. framePoints[field][anim][dir][i] = per-frame px points (excavator bucketPoints, dump_truck '
                'bedPoints / tipPoints). excavator dig: digFrame / dumpFrame (+ digPoint / dumpPoint = ground point '
                'under the bucket; it swings LEFT, away from the camera, to dump); dump_truck tip: tipFrame + tipPoint '
                '+ pileFrame (place dump_pile at tipPoint). Loaded dump truck = its idle / move frame + the cargo '
                'overlay frame cargo_{anim}_{dir}_{i} drawn on top (characters.dump_truck.cargoOverlay).',
    'demolition': 'demolitionLayout[S|M|L].sides[Y- | X+ | X- | Y+] = where the excavator (heading into the plot, '
                  'digging over the fence from the street side) and the dump truck (behind it) stand for a plot whose '
                  'street is on that side; .default = Y- (fronts face -Y). gateIndex = the fenceRings piece to leave '
                  'out. Front sides (Y-, X+) keep the bite visible; back sides are allowed (digVisible false).',
}


# --------------------------------------------------------------------------- pack

def quantize(sheet):
    import imagequant
    return imagequant.quantize_pil_image(sheet, dithering_level=0.6, max_quality=100, min_quality=0, max_colors=256)


def pack_groups(groups):
    out = []
    for g in ATLAS_ORDER + sorted(set(groups) - set(ATLAS_ORDER)):
        if g not in groups:
            continue
        builds = sorted(groups[g], key=lambda fr: -sum(im.width * im.height for _, im in fr))
        sheets = []
        for fr in builds:
            placed = False
            for sh in sheets:
                sheet, _ = pu.pack_atlas(sh + fr, max_width=MAX_SHEET, trim=True, padding=2)
                if sheet.height <= MAX_SHEET:
                    sh.extend(fr)
                    placed = True
                    break
            if not placed:
                sheets.append(list(fr))
        for i, sh in enumerate(sheets):
            sheet, atlas = pu.pack_atlas(sh, max_width=MAX_SHEET, trim=True, padding=2)
            out.append((g if i == 0 else '%s_%d' % (g, i + 1), sheet, atlas))
    return out


def guard(cache, have, need, allow_partial):
    have = set(have)
    if not have:
        raise SystemExit('civ_pack: ABORT - no complete renders in the cache %s; nothing was written (an empty '
                         'manifest is never written). Run civ_render.py first. / 렌더 캐시가 비어 있습니다.' % cache)
    missing = sorted(set(need) - have)
    if not missing:
        return []
    if allow_partial:
        print('civ_pack: WARNING --allow-partial: dropping %d key(s) not in the cache: %s' % (len(missing),
                                                                                           ' '.join(missing)))
        return missing
    raise SystemExit('civ_pack: ABORT - %d key(s) of the current manifest / civ_check.REQUIRED are missing from the '
                     'render cache %s; packing now would DELETE them. Nothing was written.\n    %s\n  fix: '
                     '/tmp/bvenv/bin/python tools/blender/civ_render.py -- <keys>  (or --allow-partial) / '
                     '캐시에 없는 키가 있어 중단합니다.' % (len(missing), cache, ' '.join(missing)))


def main(argv=None):
    argv = list(sys.argv[1:] if argv is None else argv)
    cache = os.path.join(tempfile.gettempdir(), 'fv_cache', 'civic')
    mode, previews, partial = 'on', True, False
    out_dir, prev_dir = OUT, PREV
    i = 0
    while i < len(argv):
        a = argv[i]
        if a == '--cache':
            cache = argv[i + 1]
            i += 1
        elif a == '--quantize':
            mode = argv[i + 1]
            i += 1
        elif a == '--no-previews':
            previews = False
        elif a == '--allow-partial':
            partial = True
        elif a == '--out':
            out_dir = argv[i + 1]
            i += 1
        elif a == '--prev':
            prev_dir = argv[i + 1]
            i += 1
        i += 1
    builds, vehicles = load(cache)
    import civ_decals as CD
    decals = CD.make_all()
    have = set(vehicles) | set(decals)
    for k, m in builds.items():
        have.add(k)
        have |= set((m.get('sprites') or {}).keys())
        if m.get('cutaway'):
            have |= {'%s_%s' % (k, lay) for lay in m['cutaway']['layers']}
        have |= {'%s_%s' % (k, n) for n in m.get('overlays', {})}
    have.add('furniture_pile')
    import civ_check as cc
    man_path = os.path.join(out_dir, 'manifest.json')
    old = json.load(open(man_path)) if os.path.exists(man_path) else None
    in_manifest = set((old or {}).get('characters', {})) | set((old or {}).get('sprites', {}))
    guard(cache, have, in_manifest | set(cc.REQUIRED), partial)
    # ---- images
    frames, groups = {}, {}
    for k, m in builds.items():
        imgs = build_images(cache, m)
        if m.get('cutaway'):
            m['revealPoly'] = reveal_poly(imgs['%s_shell' % k], m['anchorPx'])
        frames.update(imgs)
        smoke = set()
        if not m.get('cutaway') and 'smoke' in m.get('overlays', {}):
            smoke = set(m['overlays']['smoke']['frames'])
            groups.setdefault('civ_smoke', []).append([(n, im) for n, im in imgs.items() if n in smoke])
        groups.setdefault(m['atlas'], []).append([(n, im) for n, im in imgs.items() if n not in smoke])
    for k, (im, meta) in decals.items():
        frames[k] = im
        groups.setdefault('civ_decals', []).append([(k, im)])
    sheets = pack_groups(groups)
    vimgs = {}
    for k in VEH_KEYS:
        if k in vehicles:
            vimgs[k] = veh_images(cache, k, vehicles[k])
            sheet, atlas = pu.pack_atlas(list(vimgs[k].items()), max_width=MAX_SHEET, trim=True, padding=2)
            sheets.append(('civ_' + k, sheet, atlas))
    for akey, sheet, atlas in sheets:
        if sheet.width > MAX_SHEET or sheet.height > MAX_SHEET:
            raise SystemExit('civ_pack: atlas %s is %dx%d (> %d)' % (akey, sheet.width, sheet.height, MAX_SHEET))
    os.makedirs(out_dir, exist_ok=True)
    for fn in os.listdir(out_dir):
        if fn.startswith('civ_') and fn.endswith(('.png', '.json')):
            os.remove(os.path.join(out_dir, fn))
    total = 0
    fa = {}
    for akey, sheet, atlas in sheets:
        png = os.path.join(out_dir, akey + '.png')
        jsn = os.path.join(out_dir, akey + '.json')
        pu.save_atlas(sheet, atlas, png, jsn, quantize=False)
        if mode in ('on', 'auto') and akey.split('_2')[0] not in RGBA_ATLASES:
            try:
                quantize(sheet).save(png, optimize=True)
            except ImportError:
                print('  imagequant not installed -> kept RGBA (pip install imagequant)')
        sz = os.path.getsize(png) + os.path.getsize(jsn)
        total += sz
        for n in atlas['frames']:
            fa[n] = akey
        print('%-18s %4dx%-4d %3d frames %7.1f KB' % (akey, sheet.width, sheet.height, len(atlas['frames']),
                                                     sz / 1024.0))
    # ---- manifest
    sprites, chars = {}, {}
    order = sorted(builds, key=lambda k: (ATLAS_ORDER.index(builds[k]['atlas']) if builds[k]['atlas'] in ATLAS_ORDER
                                          else 99, k))
    for k in order:
        sprites.update(entries_for(k, builds[k], fa))
    if 'furniture_pile_l' in sprites:
        sprites['furniture_pile'] = dict(sprites['furniture_pile_l'], aliasOf='furniture_pile_l')
    for k, (im, meta) in decals.items():
        sprites[k] = {'atlas': fa[k], 'frame': k, 'anchor': meta['anchor'], 'frameSize': meta['frameSize'],
                      'kind': 'decal', 'footprint': meta['footprint'], 'radiusM': meta['radiusM'],
                      'plotM': meta['plotM'], 'layer': 'ground', 'zone': 'ruins',
                      'name': {'ko': '그을음 자국 (%s)' % k[-1].upper(), 'en': 'Scorch decal %s' % k[-1].upper()},
                      'notes': ('Soot-stained snow of a burnt %s plot (procedural): soft charcoal smudge, wet '
                                'melted ring, ash flecks. Ground layer under ruin_%s / rubble / the site; fade it out '
                                'slowly after the rebuild.' % (k[-1].upper(), k[-1]))}
    for k in VEH_KEYS:
        if k in vehicles:
            chars[k] = veh_entry(k, vehicles[k], 'civ_' + k)
            chars[k]['name'] = {'excavator': {'ko': '굴착기', 'en': 'Excavator'},
                                'dump_truck': {'ko': '덤프트럭', 'en': 'Dump truck'}}[k]
            chars[k]['zone'] = 'demolition'
    man = dict(old) if old else {}
    man['version'] = 1
    man['generator'] = 'tools/blender/civ_render.py + civ_pack.py (docs/CONTRACT_V8.md section AB)'
    man['conventions'] = CONVENTIONS
    man['atlases'] = [{'key': a, 'png': 'civic/%s.png' % a, 'json': 'civic/%s.json' % a} for a, _, _ in sheets]
    oldsp, oldch = (old or {}).get('sprites', {}), (old or {}).get('characters', {})
    man['sprites'] = {k: dict(oldsp.get(k, {}), **v) for k, v in sprites.items()}
    man['characters'] = {k: dict(oldch.get(k, {}), **v) for k, v in chars.items()}
    man['fenceRings'] = fence_rings()
    man['demolitionLayout'] = demolition_layout(vehicles, vimgs, frames, builds)
    man['fireSequence'] = FIRE_SEQUENCE
    man['ruinFor'] = RUIN_FOR
    if not man['sprites'] and not man['characters']:
        raise SystemExit('civ_pack: refusing to write an empty manifest')
    with open(man_path, 'w') as f:
        json.dump(man, f, indent=1, ensure_ascii=False)
    total += os.path.getsize(man_path)
    print('assets/civic: %d sprites, %d vehicles, %d atlases, payload %.2f MB (budget %.1f MB)'
          % (len(man['sprites']), len(man['characters']), len(sheets), total / 1048576.0, BUDGET_MB))
    if previews:
        import civ_preview as cp
        cp.make_all(out_dir, prev_dir)


if __name__ == '__main__':
    main()
